version: '3'

services:
  node-app:
    build:
      .
      # context: ./server
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
    volumes:
      - mongo-db:/data/db
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=keng
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
  redis:
    image: redis

volumes:
  mongo-db:
